// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pbft.proto

package pbft

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pbft_ExecuteTransaction_FullMethodName = "/pbft.Pbft/ExecuteTransaction"
	Pbft_SetStatus_FullMethodName          = "/pbft.Pbft/SetStatus"
	Pbft_SetByzantine_FullMethodName       = "/pbft.Pbft/SetByzantine"
	Pbft_PrePrepare_FullMethodName         = "/pbft.Pbft/PrePrepare"
	Pbft_Prepare_FullMethodName            = "/pbft.Pbft/Prepare"
	Pbft_Commit_FullMethodName             = "/pbft.Pbft/Commit"
	Pbft_Checkpoint_FullMethodName         = "/pbft.Pbft/Checkpoint"
	Pbft_ViewChange_FullMethodName         = "/pbft.Pbft/ViewChange"
	Pbft_NewView_FullMethodName            = "/pbft.Pbft/NewView"
	Pbft_Reset_FullMethodName              = "/pbft.Pbft/Reset"
	Pbft_GetBalance_FullMethodName         = "/pbft.Pbft/GetBalance"
	Pbft_GetStatus_FullMethodName          = "/pbft.Pbft/GetStatus"
	Pbft_GetTransactionLog_FullMethodName  = "/pbft.Pbft/GetTransactionLog"
	Pbft_PCPrepare_FullMethodName          = "/pbft.Pbft/PCPrepare"
	Pbft_PCPrepareReply_FullMethodName     = "/pbft.Pbft/PCPrepareReply"
	Pbft_PCCommit_FullMethodName           = "/pbft.Pbft/PCCommit"
	Pbft_GetDatastore_FullMethodName       = "/pbft.Pbft/GetDatastore"
)

// PbftClient is the client API for Pbft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PbftClient interface {
	ExecuteTransaction(ctx context.Context, in *SignedClientRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SetStatus(ctx context.Context, in *wrappers.BoolValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	SetByzantine(ctx context.Context, in *wrappers.BoolValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	PrePrepare(ctx context.Context, in *PrePrepareRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	Checkpoint(ctx context.Context, in *SignedCheckpointRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ViewChange(ctx context.Context, in *SignedViewChangeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	NewView(ctx context.Context, in *SignedNewViewRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Reset(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*DataResponse, error)
	GetTransactionLog(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DataResponse, error)
	PCPrepare(ctx context.Context, in *PCPrepareReq, opts ...grpc.CallOption) (*PCReply, error)
	PCPrepareReply(ctx context.Context, in *PCReply, opts ...grpc.CallOption) (*empty.Empty, error)
	PCCommit(ctx context.Context, in *PCPrepareReq, opts ...grpc.CallOption) (*PCReply, error)
	GetDatastore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Datastore, error)
}

type pbftClient struct {
	cc grpc.ClientConnInterface
}

func NewPbftClient(cc grpc.ClientConnInterface) PbftClient {
	return &pbftClient{cc}
}

func (c *pbftClient) ExecuteTransaction(ctx context.Context, in *SignedClientRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Pbft_ExecuteTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) SetStatus(ctx context.Context, in *wrappers.BoolValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, Pbft_SetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) SetByzantine(ctx context.Context, in *wrappers.BoolValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, Pbft_SetByzantine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) PrePrepare(ctx context.Context, in *PrePrepareRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Pbft_PrePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, Pbft_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, Pbft_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) Checkpoint(ctx context.Context, in *SignedCheckpointRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Pbft_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) ViewChange(ctx context.Context, in *SignedViewChangeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Pbft_ViewChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) NewView(ctx context.Context, in *SignedNewViewRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Pbft_NewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) Reset(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Pbft_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, Pbft_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, Pbft_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) GetTransactionLog(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, Pbft_GetTransactionLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) PCPrepare(ctx context.Context, in *PCPrepareReq, opts ...grpc.CallOption) (*PCReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PCReply)
	err := c.cc.Invoke(ctx, Pbft_PCPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) PCPrepareReply(ctx context.Context, in *PCReply, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Pbft_PCPrepareReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) PCCommit(ctx context.Context, in *PCPrepareReq, opts ...grpc.CallOption) (*PCReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PCReply)
	err := c.cc.Invoke(ctx, Pbft_PCCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) GetDatastore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Datastore, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Datastore)
	err := c.cc.Invoke(ctx, Pbft_GetDatastore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PbftServer is the server API for Pbft service.
// All implementations must embed UnimplementedPbftServer
// for forward compatibility.
type PbftServer interface {
	ExecuteTransaction(context.Context, *SignedClientRequest) (*empty.Empty, error)
	SetStatus(context.Context, *wrappers.BoolValue) (*wrappers.BoolValue, error)
	SetByzantine(context.Context, *wrappers.BoolValue) (*wrappers.BoolValue, error)
	PrePrepare(context.Context, *PrePrepareRequest) (*empty.Empty, error)
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	Checkpoint(context.Context, *SignedCheckpointRequest) (*empty.Empty, error)
	ViewChange(context.Context, *SignedViewChangeRequest) (*empty.Empty, error)
	NewView(context.Context, *SignedNewViewRequest) (*empty.Empty, error)
	Reset(context.Context, *empty.Empty) (*empty.Empty, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*DataResponse, error)
	GetTransactionLog(context.Context, *empty.Empty) (*DataResponse, error)
	PCPrepare(context.Context, *PCPrepareReq) (*PCReply, error)
	PCPrepareReply(context.Context, *PCReply) (*empty.Empty, error)
	PCCommit(context.Context, *PCPrepareReq) (*PCReply, error)
	GetDatastore(context.Context, *empty.Empty) (*Datastore, error)
	mustEmbedUnimplementedPbftServer()
}

// UnimplementedPbftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPbftServer struct{}

func (UnimplementedPbftServer) ExecuteTransaction(context.Context, *SignedClientRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTransaction not implemented")
}
func (UnimplementedPbftServer) SetStatus(context.Context, *wrappers.BoolValue) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedPbftServer) SetByzantine(context.Context, *wrappers.BoolValue) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetByzantine not implemented")
}
func (UnimplementedPbftServer) PrePrepare(context.Context, *PrePrepareRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrePrepare not implemented")
}
func (UnimplementedPbftServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPbftServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPbftServer) Checkpoint(context.Context, *SignedCheckpointRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedPbftServer) ViewChange(context.Context, *SignedViewChangeRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewChange not implemented")
}
func (UnimplementedPbftServer) NewView(context.Context, *SignedNewViewRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewView not implemented")
}
func (UnimplementedPbftServer) Reset(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedPbftServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedPbftServer) GetStatus(context.Context, *GetStatusRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPbftServer) GetTransactionLog(context.Context, *empty.Empty) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionLog not implemented")
}
func (UnimplementedPbftServer) PCPrepare(context.Context, *PCPrepareReq) (*PCReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PCPrepare not implemented")
}
func (UnimplementedPbftServer) PCPrepareReply(context.Context, *PCReply) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PCPrepareReply not implemented")
}
func (UnimplementedPbftServer) PCCommit(context.Context, *PCPrepareReq) (*PCReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PCCommit not implemented")
}
func (UnimplementedPbftServer) GetDatastore(context.Context, *empty.Empty) (*Datastore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatastore not implemented")
}
func (UnimplementedPbftServer) mustEmbedUnimplementedPbftServer() {}
func (UnimplementedPbftServer) testEmbeddedByValue()              {}

// UnsafePbftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PbftServer will
// result in compilation errors.
type UnsafePbftServer interface {
	mustEmbedUnimplementedPbftServer()
}

func RegisterPbftServer(s grpc.ServiceRegistrar, srv PbftServer) {
	// If the following call pancis, it indicates UnimplementedPbftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pbft_ServiceDesc, srv)
}

func _Pbft_ExecuteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).ExecuteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_ExecuteTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).ExecuteTransaction(ctx, req.(*SignedClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.BoolValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_SetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).SetStatus(ctx, req.(*wrappers.BoolValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_SetByzantine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.BoolValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).SetByzantine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_SetByzantine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).SetByzantine(ctx, req.(*wrappers.BoolValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_PrePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).PrePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_PrePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).PrePrepare(ctx, req.(*PrePrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).Checkpoint(ctx, req.(*SignedCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_ViewChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedViewChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).ViewChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_ViewChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).ViewChange(ctx, req.(*SignedViewChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_NewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedNewViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).NewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_NewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).NewView(ctx, req.(*SignedNewViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).Reset(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_GetTransactionLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).GetTransactionLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_GetTransactionLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).GetTransactionLog(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_PCPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PCPrepareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).PCPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_PCPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).PCPrepare(ctx, req.(*PCPrepareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_PCPrepareReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PCReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).PCPrepareReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_PCPrepareReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).PCPrepareReply(ctx, req.(*PCReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_PCCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PCPrepareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).PCCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_PCCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).PCCommit(ctx, req.(*PCPrepareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_GetDatastore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).GetDatastore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_GetDatastore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).GetDatastore(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Pbft_ServiceDesc is the grpc.ServiceDesc for Pbft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pbft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbft.Pbft",
	HandlerType: (*PbftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTransaction",
			Handler:    _Pbft_ExecuteTransaction_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _Pbft_SetStatus_Handler,
		},
		{
			MethodName: "SetByzantine",
			Handler:    _Pbft_SetByzantine_Handler,
		},
		{
			MethodName: "PrePrepare",
			Handler:    _Pbft_PrePrepare_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _Pbft_Prepare_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Pbft_Commit_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _Pbft_Checkpoint_Handler,
		},
		{
			MethodName: "ViewChange",
			Handler:    _Pbft_ViewChange_Handler,
		},
		{
			MethodName: "NewView",
			Handler:    _Pbft_NewView_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Pbft_Reset_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Pbft_GetBalance_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Pbft_GetStatus_Handler,
		},
		{
			MethodName: "GetTransactionLog",
			Handler:    _Pbft_GetTransactionLog_Handler,
		},
		{
			MethodName: "PCPrepare",
			Handler:    _Pbft_PCPrepare_Handler,
		},
		{
			MethodName: "PCPrepareReply",
			Handler:    _Pbft_PCPrepareReply_Handler,
		},
		{
			MethodName: "PCCommit",
			Handler:    _Pbft_PCCommit_Handler,
		},
		{
			MethodName: "GetDatastore",
			Handler:    _Pbft_GetDatastore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbft.proto",
}
